### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by blmage** [camiloaa/duolingonextlesson#13]
Thanks for your work on this userscript!

I'm currently toying with the idea of a browser extension that would do more or less the same thing, with an emphasis on customizability, and your staircase algorithm would definitely be an interesting addition - of course, if it's OK with you, and with all due credit.

Would you mind adding a LICENSE file to the repository, to clarify the possibility/requirements for reuse?

**Comment by camiloaa** [comment]
Honestly, the current implementation of the staircase algorithm is not very good, there is a pull request with better and cleaner code from an actual javascript programmer, that I've been not able to merge because it would break user customization. The main problem with the current algorithm, is that the slope is not a real slope, so the same value will produce different results depending on the length of the tree, and if you want to make it easy to customize, it should be easy for the user to visualize the effect of changes in the values. Something like: how many active *rows* or *lessons* do I want to have at a given time, instead of how many segments should I split the tree into. 

Pull request in question:
https://github.com/camiloaa/duolingonextlesson/pull/9/commits/fce92951e8865cd93c7d45014e951644174725fd

License in commit 76004627

**Comment by blmage** [comment]
Thank you very much for the detailed answer and the license! I'll check the PR soon, and will give more thoughts then about what kind of options we might want to leave to the user.
